"use client"

import { SubscriptionContextProvider } from '@/context/Subscriptions'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '800cal Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://upload-widget.cloudinary.com/global/all.js"
          onLoad={() => {
            console.log('Script has loaded')
          }} />
      </head>
      <SubscriptionContextProvider>
        <body className={"Lexend"}>{children}</body>
      </SubscriptionContextProvider>
    </html>
  )
}
